version: '3'

services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Jakarta
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    build: .
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./postgresql-42.6.0.jar:/usr/share/logstash/postgresql-42.6.0.jar
    environment:
      - "xpack.monitoring.enabled=false"
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
      - postgres

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
